//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ImageViewer.rc
//
#define IDC_MYICON                      2
#define IDTEST                          3
#define IDD_IMAGEVIEWER_DIALOG          102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_IMAGEVIEWER                 107
#define IDI_SMALL                       108
#define IDC_IMAGEVIEWER                 109
#define IDR_MAINFRAME                   128
#define IDD_CAPTUREOPTION               130
#define IDD_CAMERACTRL                  131
#define IDD_THRESHOLD                   133
#define IDD_BLUR                        134
#define IDD_CANNYEDGE                   135
#define IDD_LINESDET                    136
#define IDC_DISPLAYVIDEO                1000
#define IDC_USEFTP                      1001
#define IDC_SAVEIMAGE                   1002
#define IDC_EDITUSER                    1003
#define IDC_EDITFTPSERVER               1004
#define IDC_EDITPWD                     1005
#define IDC_EDITFOLDER                  1006
#define IDC_EDITNAME                    1007
#define IDC_STATICUSER                  1008
#define IDC_STATICPWD                   1009
#define IDC_STATICFTPSERVER             1010
#define IDC_STATICFOLDER                1011
#define IDC_STATICNAME                  1012
#define IDC_BUTTONSELECT                1013
#define IDC_ELABORATE                   1014
#define IDC_EDITFTPPORT                 1015
#define IDC_STATICFTPPORT               1016
#define IDC_STATICIP                    1017
#define IDC_EDITIP1                     1018
#define IDC_BUTTONDOWN                  1018
#define IDC_BUTTONRIGHT                 1019
#define IDC_SLIDER                      1019
#define IDC_BUTTONLEFT                  1020
#define IDC_EDITKSIZE                   1020
#define IDC_SLIDER2                     1020
#define IDC_BUTTONUP                    1021
#define IDC_BUTTONHOME                  1022
#define IDC_BUTTONPAN                   1023
#define IDC_BUTTONTILT                  1024
#define IDC_BUTTONSTOP                  1024
#define IDC_STATICIP2                   1025
#define IDC_STATICIP3                   1026
#define IDC_STATICIP4                   1027
#define IDC_RADIO_CONSTANT              1027
#define IDC_RADIO_BLUR                  1027
#define IDC_RADIO_REFLECT               1028
#define IDC_RADIO_GAUSSIANBLUR          1028
#define IDC_EDITIP2                     1029
#define IDC_RADIO_REPLICATE             1029
#define IDC_RADIO_MEDIANBLUR            1029
#define IDC_SLIDER1                     1029
#define IDC_EDITIP3                     1030
#define IDC_RADIO_WRAP                  1030
#define IDC_EDIT_RHO                    1030
#define IDC_EDITIP4                     1031
#define IDC_RADIO_DEFAULT               1031
#define IDC_EDIT_TETA                   1031
#define IDC_RADIO6                      1032
#define IDC_RADIO_ISOLATED              1032
#define IDC_EDIT_THRESH                 1032
#define IDC_SLIDER_THR                  1033
#define ID_FILE_OPEN32781               32781
#define ID_FILE_SAVE32782               32782
#define ID_CAPTURE_S                    32783
#define ID_CAPTURE_STOP                 32784
#define ID_CAPTURE_OPTION               32785
#define ID_CAPTURE_VIEW32786            32786
#define ID_VIEW_GRID32787               32787
#define ID_VIEW_MARKERCENTER32788       32788
#define ID_VIEW_ZOOM32789               32789
#define ID_VIEW_ZOOM32790               32790
#define ID_FILE_OPEN                    32791
#define ID_FILE_SAVE                    32792
#define ID_CAPTURE_START                32793
#define ID_VIEW_GRID                    32794
#define ID_VIEW_MARKERCENTER            32795
#define ID_VIEW_ZOOMPIU                 32796
#define ID_VIEW_ZOOMMENO                32797
#define ID_VIEW_POSE                    32798
#define ID_VIEW_RESETZOOM               32799
#define ID_FILTER_THRESHOLD             32800
#define ID_FILTER_BLUR                  32801
#define ID_FILTER_RESETALL              32802
#define ID_RESET_THRESHOLD              32803
#define ID_RESET_BLUR                   32804
#define ID_RESET_ALL                    32805
#define ID_FILTER_B                     32806
#define ID_RESET_B                      32807
#define ID_FILTER_BN                    32808
#define ID_RESET_BN                     32809
#define ID_FILTER_ERODE                 32810
#define ID_FILTER_DILATE                32811
#define ID_FILTER_LAPLACIAN             32812
#define ID_RESET_ERODE                  32813
#define ID_RESET_DILATE                 32814
#define ID_RESET_LAPLACIAN              32815
#define ID_DETECTION_EDGEDETECTION      32816
#define ID_DETECTION_LINESDETECTION     32817
#define ID_DETECTION_LINESDETECTION32818 32818
#define ID_DETECTION_LINESDETECTION2    32819
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32820
#define _APS_NEXT_CONTROL_VALUE         1034
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
